### PR TITLE
Create README_CN.md

### PR DESCRIPTION
**Pull request by iceBear67**

### CODE REVIEW

**Comment by iceBear67** [comment]
@Tacther

**Comment by Tacther** [comment]
叫你先人干啥，What do you call dad？

**Comment by iceBear67** [comment]
silly man do you know how to use pull request?

**Comment by Tacther** [comment]
oh,i don't know it,because i am a silly man,aren't i?big man.

**Comment by Tacther** [comment]
then?

**Comment by Tacther** [comment]
you are nb(adj.)

**Comment by Tacther** [comment]
对呀，我不会收，然后呢

**Comment by Tacther** [comment]
bb完了，又能怎么样

**Comment by Tacther** [comment]
反正我是一个silly man

**Comment by Tacther** [comment]
bb was done

**Comment by NaturalSelect** [comment]
Amazing dialogue

**Pull request closed without merging**
